spring:
  jpa:
    show-sql: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    name: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}


  flyway:
    locations: db/migration/base,db/migration/dev