spring:
  jpa:
    hibernate:
      ddl-auto: validate

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/realms/spring-realm/protocol/openid-connect/certs

server:
  port: 8080