INSERT INTO movie_catalog.tickets (user_id,
                                   status,
                                   purchase_time,
                                   seat_row,
                                   seat_column,
                                   price,
                                   movie_schedule_id)
VALUES ('123e4567-e89b-12d3-a456-426614174001',
        'BOOKED',
        '2023-12-20 15:00:00',
        4,
        4,
        8.99,
        1);

INSERT INTO movie_catalog.tickets (user_id,
                                   status,
                                   purchase_time,
                                   seat_row,
                                   seat_column,
                                   price,
                                   movie_schedule_id)
VALUES ('123e4567-e89b-12d3-a456-426614174001',
        'BOOKED',
        '2023-12-20 15:00:00',
        3,
        4,
        10.00,
        1);

INSERT INTO movie_catalog.tickets (user_id,
                                   status,
                                   purchase_time,
                                   seat_row,
                                   seat_column,
                                   price,
                                   movie_schedule_id)
VALUES ('123e4567-e89b-12d3-a456-426614174001',
        'CANCELED',
        '2023-12-20 15:00:00',
        2,
        2,
        15.00,
        1);

INSERT INTO movie_catalog.tickets (user_id,
                                   status,
                                   purchase_time,
                                   seat_row,
                                   seat_column,
                                   price,
                                   movie_schedule_id)
VALUES ('123e4567-e89b-12d3-a456-426614174001',
        'BOOKED',
        '2023-12-20 15:00:00',
        3,
        4,
        10.00,
        2);

INSERT INTO movie_catalog.tickets (user_id,
                                   status,
                                   purchase_time,
                                   seat_row,
                                   seat_column,
                                   price,
                                   movie_schedule_id)
VALUES ('123e4567-e89b-12d3-a456-426614174001',
        'TEMPORARY_BOOKED',
        '2023-12-20 15:00:00',
        2,
        4,
        12.00,
        2);

INSERT INTO movie_catalog.tickets (user_id,
                                   status,
                                   purchase_time,
                                   seat_row,
                                   seat_column,
                                   price,
                                   movie_schedule_id)
VALUES ('123e4567-e89b-12d3-a456-426614174001',
        'TEMPORARY_BOOKED',
        '2023-12-20 15:00',
        1,
        4,
        13.00,
        2);

INSERT INTO movie_catalog.tickets (user_id,
                                   status,
                                   purchase_time,
                                   seat_row,
                                   seat_column,
                                   price,
                                   movie_schedule_id)
VALUES ('123e4567-e89b-12d3-a456-426614174001',
        'BOOKED',
        '2023-12-20 15:00:00',
        3,
        4,
        12.00,
        3);

INSERT INTO movie_catalog.tickets (user_id,
                                   status,
                                   purchase_time,
                                   seat_row,
                                   seat_column,
                                   price,
                                   movie_schedule_id)
VALUES ('123e4567-e89b-12d3-a456-426614174001',
        'BOOKED',
        '2023-12-20 15:00:00',
        3,
        4,
        8.99,
        4);
INSERT INTO movie_catalog.tickets (user_id,
                                   status,
                                   purchase_time,
                                   seat_row,
                                   seat_column,
                                   price,
                                   movie_schedule_id)
VALUES ('123e4567-e89b-12d3-a456-426614174001',
        'BOOKED',
        '2023-12-20 15:00:00',
        3,
        5,
        8.99,
        4);

INSERT INTO movie_catalog.tickets (user_id,
                                   status,
                                   purchase_time,
                                   seat_row,
                                   seat_column,
                                   price,
                                   movie_schedule_id)
VALUES ('123e4567-e89b-12d3-a456-426614174001',
        'BOOKED',
        '2023-12-20 15:00:00',
        3,
        5,
        8.99,
        5);

INSERT INTO movie_catalog.tickets (user_id,
                                   status,
                                   purchase_time,
                                   seat_row,
                                   seat_column,
                                   price,
                                   movie_schedule_id)
VALUES ('123e4567-e89b-12d3-a456-426614174001',
        'BOOKED',
        '2023-12-20 15:00:00',
        3,
        5,
        8.99,
        6);

INSERT INTO movie_catalog.tickets (user_id,
                                   status,
                                   purchase_time,
                                   seat_row,
                                   seat_column,
                                   price,
                                   movie_schedule_id)
VALUES ('123e4567-e89b-12d3-a456-426614174001',
        'BOOKED',
        '2023-12-20 15:00:00',
        3,
        5,
        8.99,
        7);

INSERT INTO movie_catalog.tickets (user_id,
                                   status,
                                   purchase_time,
                                   seat_row,
                                   seat_column,
                                   price,
                                   movie_schedule_id)
VALUES ('123e4567-e89b-12d3-a456-426614174001',
        'BOOKED',
        '2023-12-20 15:00:00',
        3,
        5,
        8.99,
        8);
INSERT INTO movie_catalog.tickets (user_id,
                                   status,
                                   purchase_time,
                                   seat_row,
                                   seat_column,
                                   price,
                                   movie_schedule_id)
VALUES ('123e4567-e89b-12d3-a456-426614174001',
        'BOOKED',
        '2023-12-20 15:00:00',
        3,
        6,
        8.99,
        8);

INSERT INTO movie_catalog.tickets (user_id,
                                   status,
                                   purchase_time,
                                   seat_row,
                                   seat_column,
                                   price,
                                   movie_schedule_id)
VALUES ('123e4567-e89b-12d3-a456-426614174001',
        'BOOKED',
        '2023-12-20 15:00:00',
        3,
        5,
        8.99,
        9);

INSERT INTO movie_catalog.tickets (user_id,
                                   status,
                                   purchase_time,
                                   seat_row,
                                   seat_column,
                                   price,
                                   movie_schedule_id)
VALUES ('123e4567-e89b-12d3-a456-426614174001',
        'BOOKED',
        '2023-12-20 15:00:00',
        3,
        1,
        8.99,
        7);