version: '3.8'

services:
  movieplex-backend:
    build: .
    container_name: 'movieplex-backend'
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL:-jdbc:postgresql://movieplex-db:5432/movieplex}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      JWK_SET_URI: ${JWK_SET_URI}
      PRINCIPLE_ATTRIBUTE: ${PRINCIPLE_ATTRIBUTE}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      KEYCLOAK_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_ADMIN_REALM: ${KEYCLOAK_ADMIN_REALM}
      KEYCLOAK_ADMIN_RESOURCE: ${KEYCLOAK_ADMIN_RESOURCE}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_RESOURCE: ${KEYCLOAK_RESOURCE}
      KEYCLOAK_AUTH_SERVER_URL: ${KEYCLOAK_AUTH_SERVER_URL}
      KEYCLOAK_SECRET: ${KEYCLOAK_SECRET}
      KEYCLOAK_BASE_URL: ${KEYCLOAK_BASE_URL}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY}
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8090:8090"
    depends_on:
      movieplex-db:
        condition: service_started
      keycloak:
        condition: service_started

  movieplex-db:
    image: 'postgres:14'
    container_name: 'movieplex-db'
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-movieplex}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
    ports:
      - '5432:5432'
    volumes:
      - movieplex-db-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    container_name: "keycloak"
    command:
      - "start-dev --import-realm --http-port=8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      DB_VENDOR: ${DB_VENDOR}
      DB_ADDR: ${DB_ADDR}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - '8081:8080'
    depends_on:
      movieplex-db:
        condition: service_started

volumes:
  movieplex-db-data: